#!/usr/bin/sh

# FoxSprite Desktop Integration Module
# Copyright (C) 2016  Gabriel Rauter
#
# Licensed under the the MIT License (https://opensource.org/licenses/MIT).

if [ $# -ge 2 -a $# -lt 4 ]; then
  mkdir -p /tmp/FoxSprite
  filename=${1//\//.}$RANDOM
  if [ $# -eq 2 ]; then
    foxsprite -b --frame-range "0,0" $1 --sheet /tmp/FoxSprite/$filename.png
  elif [ $# -eq 3 ]; then
    foxsprite -b --frame-range "0,0" $1 --shrink-to "$3,$3" --sheet /tmp/FoxSprite/$filename.png
  fi
  mkdir -p $(dirname "$2"); mv /tmp/FoxSprite/$filename.png $2;
else
  echo "Parameters for foxsprite thumbnailer are: inputfile outputfile [size]"
fi
